### ISSUE TITLE
undefined method `exist?' for Dir:Class (NoMethodError)

### ISSUE THREAD

**Issue by 0xDedSec42** [macournoyer/thin#73]
After upgrading vom 1.2.11 to 1.3.0 I get the following error when trying to start thin via the init.d-script:

/usr/lib/ruby/gems/1.8/gems/thin-1.3.0/lib/thin/controllers/service.rb:8: undefined method `exist?' for Dir:Class (NoMethodError)
    from /usr/lib/ruby/gems/1.8/gems/thin-1.3.0/lib/thin/runner.rb:179:in`run_command'
    from /usr/lib/ruby/gems/1.8/gems/thin-1.3.0/lib/thin/runner.rb:151:in `run!'
    from /usr/lib/ruby/gems/1.8/gems/thin-1.3.0/bin/thin:6
    from /usr/bin/thin:19:in`load'
    from /usr/bin/thin:19

Same happens when when trying to thin install.
